package projects.minesweeper.tablero;
//import javax.swing.JButton;
import javax.swing.*;


public class Tablero extends JFrame {
//    private int cantidadFilas = 5;  // Puedes cambiarlo según tu necesidad
//    private int cantidadColumnas = 5;
      private JButton crearTablero;
    
    public Tablero() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        cantidadFilas = new javax.swing.JSlider();
        vaf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadColumnas = new javax.swing.JSlider();
        vac = new javax.swing.JLabel();
        EtiquetaCantidadDeMinas = new javax.swing.JLabel();
        CrearJuego = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido al Juego Buscaminas");

        cantidadFilas.setMajorTickSpacing(1);
        cantidadFilas.setMaximum(10);
        cantidadFilas.setMinimum(3);
        cantidadFilas.setPaintLabels(true);
        cantidadFilas.setPaintTicks(true);
        cantidadFilas.setValue(3);
        cantidadFilas.setName(""); // NOI18N
        cantidadFilas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadFilasStateChanged(evt);
            }
        });

        vaf.setText("Valor Actual de la Fila: ");
        vaf.setName("vaf"); // NOI18N

        jLabel2.setText("Cantidad de Filas:");

        jLabel3.setText("Cantidad de Columnas:");

        cantidadColumnas.setMajorTickSpacing(1);
        cantidadColumnas.setMaximum(10);
        cantidadColumnas.setMinimum(3);
        cantidadColumnas.setMinorTickSpacing(1);
        cantidadColumnas.setPaintLabels(true);
        cantidadColumnas.setPaintTicks(true);
        cantidadColumnas.setValue(3);
        cantidadColumnas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadColumnasStateChanged(evt);
            }
        });

        vac.setText("Valor Actual de la Columna: ");

        EtiquetaCantidadDeMinas.setText("  Indique la cantidad de Minas:  ");

        CrearJuego.setBackground(new java.awt.Color(153, 0, 153));
        CrearJuego.setForeground(new java.awt.Color(255, 255, 255));
        CrearJuego.setText("Jugar");
        CrearJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearJuegoActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("Cargar Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(EtiquetaCantidadDeMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vac, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 302, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CrearJuego)
                        .addGap(129, 129, 129)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidadFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(vaf)
                .addGap(30, 30, 30)
                .addComponent(vac)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCantidadDeMinas)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearJuego)
                    .addComponent(jButton1))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadFilasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadFilasStateChanged
        // TODO add your handling code here:
        //Metodo que indica la cantidad de mindas
        int valor = cantidadFilas.getValue();
        vaf.setText("Cantidad de Filas: " + valor);
        
    }//GEN-LAST:event_cantidadFilasStateChanged

    private void cantidadColumnasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadColumnasStateChanged
        int valor = cantidadColumnas.getValue();
        vac.setText("Cantidad de Columnas: " + valor);
    }//GEN-LAST:event_cantidadColumnasStateChanged

    private int validarEntrada() {
        try {
            int valor = Integer.parseInt(jTextField1.getText()); // Convertir a número
            int maxValor = Math.max((int) cantidadFilas.getValue(), (int) cantidadColumnas.getValue()); // Máximo permitido
            
            if (valor > maxValor) {
                JOptionPane.showMessageDialog(null, "El número ingresado no puede ser mayor que " + maxValor, "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.setText(""); // Limpiar el campo si el valor es inválido
                return 0;
            } else if(valor <= 0) {
                JOptionPane.showMessageDialog(null, "El número ingresado debe ser mayor que 0", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.setText(""); // Limpiar el campo si el valor es inválido
                return 0;
            }
            return valor;
        } catch (NumberFormatException e) {
            if (!jTextField1.getText().isEmpty()) { // Solo mostrar error si el campo no está vacío
                JOptionPane.showMessageDialog(null, "Por favor, ingrese solo números enteros", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.setText(""); // Limpiar el campo si no es un número
                return 0;
            }
            return 0;
        }
    }
    
    
    private void CrearJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearJuegoActionPerformed
        int cantidadMinas = validarEntrada(); 
        if(cantidadMinas>0){
            Buscaminas buscaMinas = new Buscaminas(cantidadFilas.getValue(), cantidadColumnas.getValue(), cantidadMinas);
            buscaMinas.setVisible(true);
        }    
    }//GEN-LAST:event_CrearJuegoActionPerformed

    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        validarEntrada();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Buscaminas buscaMinas = new Buscaminas();
        buscaMinas.cargarJuego();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearJuego;
    private javax.swing.JLabel EtiquetaCantidadDeMinas;
    private javax.swing.JSlider cantidadColumnas;
    private javax.swing.JSlider cantidadFilas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel vac;
    private javax.swing.JLabel vaf;
    // End of variables declaration//GEN-END:variables
}
