package proyecto.metrobuscaminas.tablero;
//import javax.swing.JButton;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;

public class Tablero extends JFrame {
//    private int cantidadFilas = 5;  // Puedes cambiarlo según tu necesidad
//    private int cantidadColumnas = 5;
      private JButton crearTablero;
    
    public Tablero() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        cantidadFilas = new javax.swing.JSlider();
        vaf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadColumnas = new javax.swing.JSlider();
        vac = new javax.swing.JLabel();
        EtiquetaCantidadDeMinas = new javax.swing.JLabel();
        CantidadMinas = new javax.swing.JLabel();
        CrearJuego = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido al Juego Buscaminas");

        cantidadFilas.setMajorTickSpacing(1);
        cantidadFilas.setMaximum(10);
        cantidadFilas.setMinimum(3);
        cantidadFilas.setPaintLabels(true);
        cantidadFilas.setPaintTicks(true);
        cantidadFilas.setValue(3);
        cantidadFilas.setName(""); // NOI18N
        cantidadFilas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadFilasStateChanged(evt);
            }
        });

        vaf.setText("Valor Actual de la Fila: ");
        vaf.setName("vaf"); // NOI18N

        jLabel2.setText("Cantidad de Filas:");

        jLabel3.setText("Cantidad de Columnas:");

        cantidadColumnas.setMajorTickSpacing(1);
        cantidadColumnas.setMaximum(10);
        cantidadColumnas.setMinimum(3);
        cantidadColumnas.setMinorTickSpacing(1);
        cantidadColumnas.setPaintLabels(true);
        cantidadColumnas.setPaintTicks(true);
        cantidadColumnas.setValue(3);
        cantidadColumnas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadColumnasStateChanged(evt);
            }
        });

        vac.setText("Valor Actual de la Columna: ");

        EtiquetaCantidadDeMinas.setText("Cantidad de Minas en el Tablero:   ");

        CantidadMinas.setText("0");

        CrearJuego.setText("jButton1");
        CrearJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EtiquetaCantidadDeMinas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantidadMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vac)
                            .addComponent(vaf))))
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CrearJuego)
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidadFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCantidadDeMinas)
                    .addComponent(CantidadMinas))
                .addGap(43, 43, 43)
                .addComponent(vaf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vac)
                .addGap(31, 31, 31)
                .addComponent(CrearJuego)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadFilasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadFilasStateChanged
        // TODO add your handling code here:
        //Metodo que indica la cantidad de mindas
        int valor = cantidadFilas.getValue();
        actualizarCantidadMinas();
        vaf.setText("Cantidad de Filas: " + valor);
        
    }//GEN-LAST:event_cantidadFilasStateChanged

    private void cantidadColumnasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadColumnasStateChanged
        // TODO add your handling code here:
          int valor = cantidadColumnas.getValue();
          actualizarCantidadMinas();
        vac.setText("Cantidad de Columnas: " + valor);
    }//GEN-LAST:event_cantidadColumnasStateChanged

    private void CrearJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearJuegoActionPerformed
        Buscamina buscaMina = new Buscamina(cantidadFilas.getValue(), cantidadColumnas.getValue(), Math.max(cantidadFilas.getValue(), cantidadColumnas.getValue()));
        buscaMina.setVisible(true);  
        crearTablero(cantidadFilas.getValue(),cantidadColumnas.getValue());
    }//GEN-LAST:event_CrearJuegoActionPerformed
    private void actualizarCantidadMinas() {
        int maxValor = Math.max(cantidadFilas.getValue(), cantidadColumnas.getValue());
        CantidadMinas.setText("Cantidad Minas: " + maxValor);
    }
    private void crearTablero(int filas, int columnas){
     System.out.println("entre");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadMinas;
    private javax.swing.JButton CrearJuego;
    private javax.swing.JLabel EtiquetaCantidadDeMinas;
    private javax.swing.JSlider cantidadColumnas;
    private javax.swing.JSlider cantidadFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel vac;
    private javax.swing.JLabel vaf;
    // End of variables declaration//GEN-END:variables
}


class Buscamina extends JFrame {
    private final JLabel labelFilas;
    private final JLabel labelColumnas;
    private final JLabel labelMinas;
    private JButton[][] botones;
    private JPanel panel;

    public Buscamina(int cantidadFilas, int cantidadColumnas, int cantidadMinas) {
        setTitle("Buscaminas");
        setSize(50 * cantidadColumnas + 50, 50 * cantidadFilas + 100); // Ajustar tamaño dinámicamente
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cierra esta ventana
        setLocationRelativeTo(null); // Centrar la ventana
        setLayout(new BorderLayout()); // Se usa un layout para manejar los componentes

        // Panel superior para mostrar la información
        JPanel infoPanel = new JPanel(new GridLayout(3, 1));
        labelFilas = new JLabel("Cantidad de filas: " + cantidadFilas);
        labelColumnas = new JLabel("Cantidad de Columnas: " + cantidadColumnas);
        labelMinas = new JLabel("Cantidad de Minas: " + cantidadMinas);
        infoPanel.add(labelFilas);
        infoPanel.add(labelColumnas);
        infoPanel.add(labelMinas);
        add(infoPanel, BorderLayout.NORTH);

        // Crear la matriz de botones
        dibujarMatrizBotones(cantidadFilas, cantidadColumnas);

        // Asegurar que el panel tiene los botones antes de agregarlo
        if (panel != null) {
            add(panel, BorderLayout.CENTER);
        }

        setVisible(true);
    }

    private void dibujarMatrizBotones(int filas, int columnas) {
        panel = new JPanel(new GridLayout(filas, columnas, 2, 2)); // ✅ Usar la variable de clase `panel`
        botones = new JButton[filas][columnas];
        CT controlador = new CT(filas, columnas);
        String[][] matriz = controlador.generarMatriz(filas, columnas);

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                final int x = i;
                final int y = j;  
                final String valorCelda = matriz[i][j];
                
                botones[i][j] = new JButton();
                botones[i][j].setText("");
                
                botones[i][j].addActionListener(new ActionListener() {
                @Override
                    public void actionPerformed(ActionEvent e) {
                        botones[x][y].setText(valorCelda); // Revelar el contenido al hacer clic
                        botones[x][y].setEnabled(false); // Deshabilitar botón después de revelarlo
                }
                });
                
                panel.add(botones[i][j]); // Agregar botón al panel
            }
        }
    }
}
